### ISSUE TITLE
Not able to access pretrained weights of chemIENER(chembert)

### ISSUE THREAD

**Issue by agent-ai-07** [CrystalEye42/OpenChemIE#10]
Error message : Some weights of BertForTokenClassification were not initialized from the model checkpoint at dmis-lab/biobert-large-cased-v1.1 and are newly initialized: ['classifier.bias','classifier.weight'] you should probably TRAIN this model on a down-stream task to able to use it for predictions and inference.

The output is printing as an empty list

**Comment by Ozymandias314** [comment]
Hello,

You may be getting an empty list for the same reason as https://github.com/Ozymandias314/ChemIENER/issues/2.
