### ISSUE TITLE
Question about using extract_molecule_corefs_from_figures

### ISSUE THREAD

**Issue by yyh030806** [CrystalEye42/OpenChemIE#11]
I get this output when using extract_molecule_corefs_from_figures:
output:
<img width="1091" alt="截屏2024-07-08 19 11 42" src="https://github.com/CrystalEye42/OpenChemIE/assets/127122695/3255668c-24e6-43c1-8954-25e636c8d315">
How can I get the identifier like README and achieve the function in the paper?
README:
<img width="715" alt="截屏2024-07-08 19 12 13" src="https://github.com/CrystalEye42/OpenChemIE/assets/127122695/d328031f-8115-4dda-9852-05a0842d2405">
paper: 
<img width="573" alt="截屏2024-07-08 19 15 52" src="https://github.com/CrystalEye42/OpenChemIE/assets/127122695/c3a5de85-7d98-4435-9f60-b5e143e81dc1">
Thanks.

**Comment by CrystalEye42** [comment]
Hello, the README was out of date and has been updated. The corefs returned are in the form `[mol bbox index, idt bbox index]`, so to get the identifier, one could do something like 
```
coref_idx = data['corefs'][i][1]
print(data['bboxes'][coref_idx]['text'])
```
