### ISSUE TITLE
OpenChemIE installation not working 

### ISSUE THREAD

**Issue by gmaikelc** [CrystalEye42/OpenChemIE#7]
conda install -c conda-forge pycocotools==2.0.4

pip install 'OpenChemIE @ git+https://github.com/CrystalEye42/OpenChemIE'
pip uninstall MolScribe
pip install --no-deps 'MolScribe @ git+https://github.com/CrystalEye42/MolScribe.git@cb08600'

The last three lines are not properly working to install OpenChemIE, any suggestions will be welcome

**Comment by CrystalEye42** [comment]
Hello, thank you for the feedback! Could you please include the error message you’re getting to help narrow down the issue?

**Comment by gmaikelc** [comment]
Hello, thanks for your quick response, my OS is W2, and this is the message that I am getting when trying to run the second line as suggested in the Readme.cmd file. 

ERROR: Invalid requirement: "'OpenChemIE"

**Comment by CrystalEye42** [comment]
One possible thing to try is directly cloning the repository and installing with the following commands:
```
git clone https://github.com/CrystalEye42/OpenChemIE.git
cd OpenChemIE
pip install .
```
and then running the 3rd and 4th lines. If this doesn't work, could you also provide the outputs of each of the following commands:
```
python --version
pip --version
pip freeze
```

**Comment by gmaikelc** [comment]
Thanks for the suggestions. I already try, but is still giving some errors, which I am sending below. Thanks again for your help on this issue. 

  Running command git clone --filter=blob:none --quiet https://github.com/thomas0809/MolScribe.git 'C:\Users\gmaikelc\AppData\Local\Temp\pip-install-861mnu95\molscribe_a58f53e069ff4075b73fffa726873db2'
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [75 lines of output]
      WARNING: pkg-config not found--guessing at poppler version.
               If the build fails, install pkg-config and try again.
      WARNING: pkg-config not found--guessing at poppler version.
               If the build fails, install pkg-config and try again.
      WARNING: pkg-config not found--guessing at poppler version.
               If the build fails, install pkg-config and try again.
      running bdist_wheel
      running build
      running build_ext
      building 'pdftotext' extension
      creating build
      creating build\temp.win-amd64-cpython-310
      creating build\temp.win-amd64-cpython-310\Release
      "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.20.27508\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -DPOPPLER_CPP_AT_LEAST_0_30_0=1 -DPOPPLER_CPP_AT_LEAST_0_58_0=1 -DPOPPLER_CPP_AT_LEAST_0_88_0=1 "-IC:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\include" "-IC:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\Include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.20.27508\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.20.27508\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /EHsc /Tppdftotext.cpp /Fobuild\temp.win-amd64-cpython-310\Release\pdftotext.obj -Wall
...
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pycocotools
ERROR: Could not build wheels for pdftotext, pycocotools, which is required to install pyproject.toml-based projects

**Comment by CrystalEye42** [comment]
Could you first install the Microsoft Visual C++ Build Tools, run the following commands, and try installing again? 
```
pip install Cmake
conda install -c conda-forge poppler
```
Can you also confirm whether or not `conda install -c conda-forge pycocotools==2.0.4` ran successfully before?

**Comment by gmaikelc** [comment]
Can you also confirm whether or not conda install -c conda-forge pycocotools==2.0.4 ran successfully before? 
This was successfully ran. 
I try the suggestions given above, but still not working. 

Thanks again for your help with this issue.

**Comment by CrystalEye42** [comment]
It looks like there are issues with installing pdftotext on Windows, there might be some useful info in this thread https://github.com/jalan/pdftotext/issues/16#issuecomment-399963100
